# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# **Run a single job*

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
# **Run a multiple job*

trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
- job: job1
  steps:
  - script: echo Hello, world from job1!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
 
- job: job2
  steps:
  - script: echo Hello, world from job1!
    displayName: 'Run a one-line script'
 
- job: job3
  steps:
  - script: echo Hello, world from job3!
    displayName: 'Run a one-line script'
# **till above in multiple job we will run jobs but its not in sequence so for sequence one by one we use **dependsOn** it will run one job after one job*
trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
- job: job1
  steps:
  - script: echo Hello, world from job1!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
 
- job: job2
  dependsOn: job1
  steps:
  - script: echo Hello, world from job1!
    displayName: 'Run a one-line script'
- job: job3
  dependsOn: job2
  steps:
  - script: echo Hello, world from job3!
    displayName: 'Run a one-line script'
 jobs:
- job: job4
  dependsOn: 
  - job2
  - job3
  steps:
  - script: echo Hello, world from job3!
    displayName: 'Run a one-line script'
   
